export const SAMPLE_BUSINESSES = [
  {
    id: "yuva",
    name: "Yuva Handmade Bags",
    owner: "A homegrown bag maker",
    language: "Tamil",
    category: "Handmade bags",
    image: "https://images.unsplash.com/photo-1637759292654-a12cb2be085e?auto=format&fit=crop&w=1200&q=85",
    video: "https://www.pexels.com/video/a-woman-makes-a-reusable-and-washable-bag-made-of-cloth-3755536/",
    quote: "இந்த பை கையால் செய்தது. விலை ஆயிரத்து இருநூறு ரூபாய். இரண்டு பைகள் உள்ளன.",
    translation: "This bag is handmade. The price is ₹1,200 and two pieces are available.",
    color: "from-amber-900/75 to-orange-700/20",
  },
  {
    id: "saree",
    name: "Lakshmi Sarees",
    owner: "A neighbourhood textile seller",
    language: "Hindi",
    category: "Handloom sarees",
    image: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1200&q=85",
    video: "https://www.youtube.com/watch?v=EBa1xspJe-E",
    quote: "यह संबलपुरी इकत सिल्क साड़ी है, कीमत ₹2,499 है और तीन रंग उपलब्ध हैं।",
    translation: "Sambalpuri ikat silk saree, ₹2,499, available in three colours.",
    color: "from-fuchsia-950/80 to-rose-700/20",
  },
  {
    id: "bakery",
    name: "Meera Home Bakery",
    owner: "A home baker",
    language: "English",
    category: "Fresh bakes",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1200&q=85",
    video: "https://www.pexels.com/video/woman-taking-picture-of-the-cake-while-using-smartphone-7551831/",
    quote: "Chocolate celebration cake, one kilo, ₹950. Pre-order one day in advance.",
    translation: "Angadi captures price, weight and fulfilment instructions.",
    color: "from-stone-950/80 to-amber-800/20",
  },
  {
    id: "crafts",
    name: "Anjali Handicrafts",
    owner: "An independent artisan",
    language: "Hindi",
    category: "Handmade décor",
    image: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=1200&q=85",
    video: "https://www.pexels.com/video/a-woman-is-sitting-on-a-bench-in-a-market-19414073/",
    quote: "ये हाथ से बने टेराकोटा दीये हैं। छह का सेट ₹450 में है।",
    translation: "Handmade terracotta diyas, set of six for ₹450.",
    color: "from-red-950/80 to-orange-700/20",
  },
];

export const SAMPLE_PRODUCTS = [
  { id: "sample-1", title: "Handcrafted Tan Shoulder Bag", description: "A warm tan everyday shoulder bag with a clean silhouette and carefully finished stitching.", category: "Handmade bags", price: 1200, stock: 2, sku: "ANG-YU01", image: "https://images.unsplash.com/photo-1637759292654-a12cb2be085e?auto=format&fit=crop&w=900&q=85", online: true },
  { id: "sample-2", title: "Natural Canvas Tote", description: "Lightweight natural canvas tote with reinforced handles for markets, work and everyday errands.", category: "Tote bags", price: 850, stock: 5, sku: "ANG-YU02", image: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=900&q=85", online: true },
  { id: "sample-3", title: "Handwoven Sling Bag", description: "Compact crossbody sling with a handwoven strap and an easy-access inner pocket.", category: "Sling bags", price: 999, stock: 3, sku: "ANG-YU03", image: "https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?auto=format&fit=crop&w=900&q=85", online: true },
];
